[ETLYN-38] - ფოტოების კარუსელი
mtielitsignebi/mtielitsignebi.ge pull request #45
Opened 2024-07-07 09:01 UTC by Alsandre

https://etlyn.atlassian.net/browse/ETLYN-38

2024-07-07 09:03 UTC, mtielitsignebi commented
🎉 Nice work, all checks have passed!

2024-07-08 20:48 UTC, digmel requested changes

2024-07-08 20:48 UTC, digmel commented on src/pages/Home/HomePage.tsx
> +          showSingleSlide={platform !== Platform.Web}
On mobile, images are so large and they are breaking layout, please add more styles. Also:
```suggestion
        <StyledCarousel
          showSingleSlide={platform === Platform.Mobile}
```

2024-07-14 22:18 UTC, digmel commented on src/pages/Home/HomePage.tsx
> +          imageList={IMAGE_LIST}
I think you should not pass IMAGE_LIST. Instead, set 'children' and keep the 'data.map' loop here. The Carousel library should animate whatever is in 'children,' whether it's an image list, a div, or cards for blogs, reviews, or other sections.

2024-07-16 02:35 UTC, mtielitsignebi commented
🎉 Nice work, all checks have passed!

2024-07-16 03:38 UTC, digmel approved these changes
Nice work!

2024-07-16 03:39 UTC, digmel commented on src/pages/Home/HomePage.tsx
> +  console.log(IMAGE_LIST)
Try not to keep any conosle.log in the PR.

2024-07-16 03:39 UTC, merged